## 특성공학과 규제

## Pandas로 데이터 준비하기

#### => conda env list
#### => conda activate mlbasic
#### => pip install pandas

In [109]:
import pandas as pd

data_url="https://bit.ly/perch_csv_data"
df=pd.read_csv(data_url)
perch_full=df.to_numpy()
print(perch_full[:3])


[[ 8.4   2.11  1.41]
 [13.7   3.53  2.  ]
 [15.    3.82  2.43]]


In [110]:
df.shape

(56, 3)

In [111]:
df.head(10)

length   height   width
0     8.4     2.11    1.41
1    13.7     3.53    2.00
2    15.0     3.82    2.43
3    16.2     4.59    2.63
4    17.4     4.59    2.94
5    18.0     5.22    3.32
6    18.7     5.20    3.12
7    19.0     5.64    3.05
8    19.6     5.14    3.04
9    20.0     5.08    2.77

In [112]:
df.tail(5)

length   height   width
51    42.0    12.80    6.87
52    43.0    11.93    7.28
53    43.0    12.51    7.42
54    43.5    12.60    8.14
55    44.0    12.49    7.60

In [113]:
df.describe()

length     height      width
count  56.000000  56.000000  56.000000
mean   27.892857   7.862143   4.745536
std     9.021668   2.878343   1.775006
min     8.400000   2.110000   1.410000
25%    21.825000   5.690000   3.520000
50%    25.300000   6.920000   4.155000
75%    36.625000  10.850000   6.450000
max    44.000000  12.800000   8.140000

In [114]:
perch_full=df.to_numpy()

In [115]:
perch_full[:3]

array([[ 8.4 ,  2.11,  1.41],
       [13.7 ,  3.53,  2.  ],
       [15.  ,  3.82,  2.43]])

In [116]:
pd.read_csv("perch_full.csv")

length   height   width
0      8.4     2.11    1.41
1     13.7     3.53    2.00
2     15.0     3.82    2.43
3     16.2     4.59    2.63
4     17.4     4.59    2.94
5     18.0     5.22    3.32
6     18.7     5.20    3.12
7     19.0     5.64    3.05
8     19.6     5.14    3.04
9     20.0     5.08    2.77
10    21.0     5.69    3.56
11    21.0     5.92    3.31
12    21.0     5.69    3.67
13    21.3     6.38    3.53
14    22.0     6.11    3.41
15    22.0     5.64    3.52
16    22.0     6.11    3.52
17    22.0     5.88    3.52
18    22.0     5.52    4.00
19    22.5     5.86    3.62
20    22.5     6.79    3.62
21    22.7     5.95    3.63
22    23.0     5.22    3.63
23    23.5     6.28    3.72
24    24.0     7.29    3.72
25    24.0     6.38    3.82
26    24.6     6.73    4.17
27    25.0     6.44    3.68
28    25.6     6.56    4.24
29    26.5     7.17    4.14
30    27.3     8.32    5.14
31    27.5     7.17    4.34
32    27.5     7.05    4.34
33    27.5     7.28    4.57
34    28.0     7.82    4.20
35    28.7     7.59    4.64
36    30.0     7.62    4.77
37    32.8    10.03    6.02
38    34.5    10.26    6.39
39    35.0    11.49    7.80
40    36.5    10.88    6.86
41    36.0    10.61    6.74
42    37.0    10.84    6.26
43    37.0    10.57    6.37
44    39.0    11.14    7.49
45    39.0    11.14    6.00
46    39.0    12.43    7.35
47    40.0    11.93    7.11
48    40.0    11.73    7.22
49    40.0    12.38    7.46
50    40.0    11.14    6.63
51    42.0    12.80    6.87
52    43.0    11.93    7.28
53    43.0    12.51    7.42
54    43.5    12.60    8.14
55    44.0    12.49    7.60

In [117]:
import numpy as np

In [118]:
perch_weight = np.array([5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 110.0,
                         115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 130.0,
                        150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 197.0,
                        218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 514.0,
                        556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 820.0,
                        850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 1000.0,
                        1000.0])


In [119]:
from sklearn.model_selection import train_test_split

In [120]:
X_train,X_test,y_train,y_test=train_test_split(perch_full,perch_weight,random_state=42)

In [121]:
from sklearn.linear_model import LinearRegression

lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [122]:
print("계수:",lr.coef_, "절편:",lr.intercept_)

계수: [ 9.07538153 69.46401443 38.00385678] 절편: -599.1708082981097


In [123]:
 ## linear regression model
 ## weight= 9.07*length+69.4*height+ 38.0*width-599.1



In [124]:
lr.score(X_train,y_train)

0.9559326821885706

In [125]:
lr.score(X_test,y_test)

0.8796419177546367

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(include_bias=False) ## include_bias=False는 1을 없애주는 코드 
poly.fit(X_train)
train_poly=poly.transform(X_train)
print(train_poly.shape)

(42, 9)


In [127]:
train_poly[0:3]

array([[ 19.6   ,   5.14  ,   3.04  , 384.16  , 100.744 ,  59.584 ,
         26.4196,  15.6256,   9.2416],
       [ 22.    ,   5.88  ,   3.52  , 484.    , 129.36  ,  77.44  ,
         34.5744,  20.6976,  12.3904],
       [ 18.7   ,   5.2   ,   3.12  , 349.69  ,  97.24  ,  58.344 ,
         27.04  ,  16.224 ,   9.7344]])

In [128]:
poly.get_feature_names_out()

array(['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2',
       'x2^2'], dtype=object)

In [129]:
test_poly=poly.transform(X_test)

In [130]:
from sklearn.linear_model import LinearRegression


In [131]:
lr.fit(X_train,y_train)

LinearRegression()

In [132]:
lr.score(X_train,y_train)

0.9559326821885706

In [133]:
lr.score(X_test,y_test)

0.8796419177546367

In [134]:

lr=LinearRegression()
lr.fit(train_poly,y_train)
print(lr.score(train_poly,y_train))
print(lr.score(test_poly,y_test)) ## 특성 공학을 이용해 특성을 더 늘려주면 성과가 좋아지는것을 알 수 있다.

0.9903183436982126
0.9714559911594125


In [ ]:
poly=PolynomialFeatures(degree=5,include_bias=False) ## degree로 변수에 대한 특성을 늘릴 수 있다.
poly.fit(X_train)

train_poly=poly.transform(X_train)
print(train_poly.shape)


(42, 34)


In [136]:
poly.get_feature_names_out()


array(['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2',
       'x2^2', 'x0^3', 'x0^2 x1', 'x0^2 x2', 'x0 x1^2', 'x0 x1 x2',
       'x0 x2^2', 'x1^3', 'x1^2 x2', 'x1 x2^2', 'x2^3', 'x0^4', 'x0^3 x1',
       'x0^3 x2', 'x0^2 x1^2', 'x0^2 x1 x2', 'x0^2 x2^2', 'x0 x1^3',
       'x0 x1^2 x2', 'x0 x1 x2^2', 'x0 x2^3', 'x1^4', 'x1^3 x2',
       'x1^2 x2^2', 'x1 x2^3', 'x2^4'], dtype=object)

In [137]:
train_poly[1]

array([2.20000000e+01, 5.88000000e+00, 3.52000000e+00, 4.84000000e+02,
       1.29360000e+02, 7.74400000e+01, 3.45744000e+01, 2.06976000e+01,
       1.23904000e+01, 1.06480000e+04, 2.84592000e+03, 1.70368000e+03,
       7.60636800e+02, 4.55347200e+02, 2.72588800e+02, 2.03297472e+02,
       1.21701888e+02, 7.28555520e+01, 4.36142080e+01, 2.34256000e+05,
       6.26102400e+04, 3.74809600e+04, 1.67340096e+04, 1.00176384e+04,
       5.99695360e+03, 4.47254438e+03, 2.67744154e+03, 1.60282214e+03,
       9.59512576e+02, 1.19538914e+03, 7.15607101e+02, 4.28390646e+02,
       2.56451543e+02, 1.53522012e+02])

In [138]:
test_poly=poly.transform(X_test)
print(test_poly.shape)

(14, 34)


In [139]:
lr.fit(train_poly,y_train)
print(lr.score(train_poly,y_train))
print(lr.score(test_poly,y_test)) ## 속성에 대해 늘려주는게 꼭 좋은것만은 아닌것을 알 수 있음

0.9995286898073679
-6.786696932218207


## 규제 

In [142]:
from sklearn.preprocessing import StandardScaler

In [143]:
ss=StandardScaler()
ss.fit(train_poly)


StandardScaler()

In [146]:
train_scaled=ss.transform(train_poly)
test_scaled=ss.transform(test_poly)

## 특성 공학(Feature Engineering)

In [140]:
from sklearn.preprocessing import PolynomialFeatures

poly=PolynomialFeatures(include_bias=False) ## 곱한 값, 제곱갑, 절편값의 계수 1

poly.fit([[2,3]]) ## 데이터를 집어넣어 훈련시킨다
values= poly.transform([[2,3]]) ## x0,x1을 변형 시킨다.
print(values) ## 2,3,4,6,9
names=poly.get_feature_names_out() ## 위의 변형시킨 데이터의 변경순서를 나타냄
print(names)
np.column_stack((names,values[0])) 

[[2. 3. 4. 6. 9.]]
['x0' 'x1' 'x0^2' 'x0 x1' 'x1^2']


array([['x0', 2.0],
       ['x1', 3.0],
       ['x0^2', 4.0],
       ['x0 x1', 6.0],
       ['x1^2', 9.0]], dtype=object)