## 5-1 Logistic Regression

In [15]:
import pandas as pd


In [16]:
url="https://bit.ly/fish_csv_data"
fish=pd.read_csv(url)

In [17]:
fish.shape

(159, 6)

In [18]:
fish.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [19]:
pd.unique(fish["Species"])

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [20]:
fish_input=fish[["Weight",	"Length",	"Diagonal",	"Height",	"Width"]]

In [21]:
fish_input[:5]

Weight  Length  Diagonal   Height   Width
0   242.0    25.4      30.0  11.5200  4.0200
1   290.0    26.3      31.2  12.4800  4.3056
2   340.0    26.5      31.1  12.3778  4.6961
3   363.0    29.0      33.5  12.7300  4.4555
4   430.0    29.0      34.0  12.4440  5.1340

In [22]:
fish_target=fish["Species"]

In [23]:
fish_target[:5]

0    Bream
1    Bream
2    Bream
3    Bream
4    Bream
Name: Species, dtype: object

In [25]:
type(fish_target)

pandas.core.series.Series

In [27]:
type(fish_input)

pandas.core.frame.DataFrame

In [28]:
fish_target=fish_target.to_numpy()
fish_input=fish_input.to_numpy()


In [30]:
type(fish_target)

numpy.ndarray

In [32]:
type(fish_input)

numpy.ndarray

In [34]:
from sklearn.model_selection import train_test_split

In [36]:
train_input, test_input, train_target, test_target=train_test_split(fish_input,fish_target,random_state=42)

In [38]:
# 정규화 -> 데이터의 속성 값의 척도(scale)이 다른 경우, 일관된 크기로 변경하기 위해서 한다.
from sklearn.preprocessing import StandardScaler
# StandardScaler 초기화
ss= StandardScaler()
# 입력 값 train_input를 받아서 정규화에  사용할 평균, 표준편차를 구한다.
ss.fit(train_input)
#각 컬럼의 값을 표준화 한다.
train_scaled=ss.transform(train_input) ## 각 칼럼의 (실제 값- 평균)/ (표준편차)를 구해준다.
test_scaled=ss.transform(test_input)


In [40]:
train_scaled[:5]

array([[ 0.91965782,  0.60943175,  0.81041221,  1.85194896,  1.00075672],
       [ 0.30041219,  1.54653445,  1.45316551, -0.46981663,  0.27291745],
       [-1.0858536 , -1.68646987, -1.70848587, -1.70159849, -2.0044758 ],
       [-0.79734143, -0.60880176, -0.67486907, -0.82480589, -0.27631471],
       [-0.71289885, -0.73062511, -0.70092664, -0.0802298 , -0.7033869 ]])

# KNearestNeighbor를 사용하여 모델링 

In [44]:
# KNN class 가져오기
from sklearn.neighbors import KNeighborsClassifier

# KNeighborsClassifier 초기화
knn=KNeighborsClassifier(n_neighbors=3)

#KNN 모델 생성
knn.fit(train_scaled,train_target)

print("학습 데이터 정확도:",knn.score(train_scaled,train_target))
print("검증 데이터 정확도:",knn.score(test_scaled,test_target))



학습 데이터 정확도: 0.8907563025210085
검증 데이터 정확도: 0.85


In [47]:
knn.classes_

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [48]:
test_scaled[:5]

array([[-0.88741352, -0.91804565, -1.03098914, -0.90464451, -0.80762518],
       [-1.06924656, -1.50842035, -1.54345461, -1.58849582, -1.93803151],
       [-0.54401367,  0.35641402,  0.30663259, -0.8135697 , -0.65388895],
       [-0.34698097, -0.23396068, -0.22320459, -0.11905019, -0.12233464],
       [-0.68475132, -0.51509149, -0.58801052, -0.8998784 , -0.50124996]])

In [50]:
knn.predict(test_scaled[:5])

array(['Perch', 'Smelt', 'Pike', 'Perch', 'Perch'], dtype=object)

In [52]:
proba=knn.predict_proba(test_scaled[:5])

In [54]:
print(proba)

[[0.         0.         1.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         1.
  0.        ]
 [0.         0.         0.         1.         0.         0.
  0.        ]
 [0.         0.         0.66666667 0.         0.33333333 0.
  0.        ]
 [0.         0.         0.66666667 0.         0.33333333 0.
  0.        ]]


In [56]:
distances, indexes=knn.kneighbors(test_scaled[3:4])

In [58]:
distances

array([[0.20774583, 0.24862983, 0.33682411]])

In [60]:
indexes

array([[104, 115, 106]])

In [62]:
train_target[indexes]

array([['Roach', 'Perch', 'Perch']], dtype=object)