## 특성공학과 규제

## Pandas로 데이터 준비하기

#### => conda env list
#### => conda activate mlbasic
#### => pip install pandas

In [32]:
import pandas as pd

data_url="https://bit.ly/perch_csv_data"
df=pd.read_csv(data_url)
perch_full=df.to_numpy()
print(perch_full[:3])


[[ 8.4   2.11  1.41]
 [13.7   3.53  2.  ]
 [15.    3.82  2.43]]


In [33]:
df.shape

(56, 3)

In [34]:
df.head(10)

length   height   width
0     8.4     2.11    1.41
1    13.7     3.53    2.00
2    15.0     3.82    2.43
3    16.2     4.59    2.63
4    17.4     4.59    2.94
5    18.0     5.22    3.32
6    18.7     5.20    3.12
7    19.0     5.64    3.05
8    19.6     5.14    3.04
9    20.0     5.08    2.77

In [35]:
df.tail(5)

length   height   width
51    42.0    12.80    6.87
52    43.0    11.93    7.28
53    43.0    12.51    7.42
54    43.5    12.60    8.14
55    44.0    12.49    7.60

In [36]:
df.describe()

length     height      width
count  56.000000  56.000000  56.000000
mean   27.892857   7.862143   4.745536
std     9.021668   2.878343   1.775006
min     8.400000   2.110000   1.410000
25%    21.825000   5.690000   3.520000
50%    25.300000   6.920000   4.155000
75%    36.625000  10.850000   6.450000
max    44.000000  12.800000   8.140000

In [37]:
perch_full=df.to_numpy()

In [38]:
perch_full[:3]

array([[ 8.4 ,  2.11,  1.41],
       [13.7 ,  3.53,  2.  ],
       [15.  ,  3.82,  2.43]])

In [39]:
##pd.read_csv("perch_full.csv")

In [40]:
import numpy as np

In [41]:
perch_weight = np.array([5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 110.0,
                         115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 130.0,
                        150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 197.0,
                        218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 514.0,
                        556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 820.0,
                        850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 1000.0,
                        1000.0])


In [42]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(perch_full,perch_weight,random_state=42)

In [48]:
from sklearn.linear_model import LinearRegression

lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [50]:
print("계수:",lr.coef_, "절편:",lr.intercept_)

계수: [ 9.07538153 69.46401443 38.00385678] 절편: -599.1708082981097


In [ ]:
# linear regression model
# weight= 9.07*length+69.4*height+ 38.0*width-599.1



In [51]:
lr.score(X_train,y_train)

0.9559326821885706

In [52]:
lr.score(X_test,y_test)

0.8796419177546367

## 특성 공학(Feature Engineering)

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

poly=PolynomialFeatures(include_bias=False) ## 곱한 값, 제곱갑, 절편값의 계수 1

poly.fit([[2,3]]) ## 데이터를 집어넣어 훈련시킨다
values= poly.transform([[2,3]]) ## x0,x1을 변형 시킨다.
print(values) ## 2,3,4,6,9
names=poly.get_feature_names_out() ## 위의 변형시킨 데이터의 변경순서를 나타냄
print(names)
np.column_stack((names,values[0])) 

[[2. 3. 4. 6. 9.]]
['x0' 'x1' 'x0^2' 'x0 x1' 'x1^2']


array([['x0', 2.0],
       ['x1', 3.0],
       ['x0^2', 4.0],
       ['x0 x1', 6.0],
       ['x1^2', 9.0]], dtype=object)